apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jkurj09sc-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jkurj09sc-java-quarkus-gitops